# Generated by Django 2.1.5 on 2019-02-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190209_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade_in_school',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='hrs_per_week_available',
            field=models.IntegerField(default=1),
        ),
    ]
