# Generated by Django 2.1.5 on 2019-02-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190210_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never Coded Before'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], null=True),
        ),
    ]
