# Generated by Django 2.1.5 on 2019-02-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychallenge',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
